#!/usr/bin/env bash

menu_args=$(printf '%b' 'Search Files\nInstall\nWallpaper\nRecord Screen\nRemove\nUpdate' | rofi -dmenu -p "Options: " -i -theme-str "window {width: 20em;}")

case "$menu_args" in
*Files)
  rofi -show recursivebrowser -theme-str 'window {width: 42em;} listview {lines: 8;}'
  ;;
*Install)
  install_args=$(printf '%b' 'Pacman\nAUR' | rofi -dmenu -p "Install: " -i -theme-str "window {width: 20em;}")
  case "$install_args" in
  *Pacman)
    ~/.local/bin/terminal-floating pkg-install
    ;;
  *AUR)
    ~/.local/bin/terminal-floating pkg-aur-install
    ;;
  esac
  ;;
*Remove)
  remove_args=$(printf '%b' 'Packages\nTUI' | rofi -dmenu -p "Remove: " -i)
  case "$remove_args" in
  *Packages)
    ~/.local/bin/terminal-floating pkg-remove
    ;;
  esac
  ;;

*Wallpaper)
  ~/.local/bin/hyprwall
  ;;
*Colorscheme)
  theme_args=$(printf '%b' 'Black Lotus\nCatppuccin Mocha\nDracula\nGruvbox Dark\nKanagawa\nRose Pine\nTokyonight' | rofi -dmenu -p 'Colorscheme: ' -i)
  case "$theme_args" in
  *Black\ Lotus)
    ~/.local/bin/rofi-theme-switcher blacklotus
    ;;
  *Catppuccin\ Mocha)
    ~/.local/bin/rofi-theme-switcher catppuccin-mocha
    ;;
  *Dracula)
    ~/.local/bin/rofi-theme-switcher dracula
    ;;
  *Gruvbox\ Dark)
    ~/.local/bin/rofi-theme-switcher gruvbox-dark
    ;;
  *Kanagawa)
    ~/.local/bin/rofi-theme-switcher kanagawa
    ;;
  *Rose\ Pine)
    ~/.local/bin/rofi-theme-switcher rose-pine
    ;;
  *Tokyonight)
    ~/.local/bin/rofi-theme-switcher tokyonight
    ;;
  esac
  ;;
*Record\ Screen)
  record_args=$(printf '%b' 'Display\nDisplay + Audio\nWebcam + Audio\nRegion\nRegion + Audio' | rofi -dmenu -p "Record: " -i -theme-str "window {width: 20em;}")
  case "$record_args" in
  *Display)
    ~/.local/bin/screenrecord output
    ;;
  *Display\ +\ Audio)
    ~/.local/bin/screenrecord output --with-audio
    ;;
  *Webcam\ +\ Audio)
    ~/.local/bin/screenrecord output --with-webcam --with-audio
    ;;
  *Region)
    ~/.local/bin/screenrecord region
    ;;
  *Region\ +\ Audio)
    ~/.local/bin/screenrecord region --with-audio
    ;;
  esac
  ;;
*Update)
  ~/.local/bin/terminal-floating pkg-update
  ;;
esac
