#!/usr/bin/env bash

hyprland_idle() {
  if pgrep -x hypridle &>/dev/null; then
    pkill -x hypridle
    notify-send "TOGGLE" "Hypridle stopped"
  else
    setsid --fork hypridle
    notify-send "TOGGLE" "Hypridle started"
  fi
}
niri_idle() {
  # Using swayidle for niri which is recommended by niri docs
  if pgrep swayidle &>/dev/null; then
    pkill swayidle
    notify-send "TOGGLE" "Swayidle stopped"
  else
    setsid --fork swayidle -w \
      "timeout" "300" "'niri' 'msg' 'action' 'power-off-monitors'" \
      "timeout" "310" "swaylock" \
      "resume" "'niri' 'msg' 'action' 'power-on-monitors'" \
      "before-sleep" "swaylock"
    notify-send "TOGGLE" "Swayidle started"
  fi
}

case "$1" in
*hyprland)
  hyprland_idle
  ;;
*niri)
  niri_idle
  ;;
esac
